FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=10000
CMD exec gunicorn --bind 0.0.0.0:$PORT app:app